version: "3"
services:
  scrape_server:
    build:
      context: ./scrape_server
      dockerfile: Dockerfile
    container_name: scrape_server_container
    tty: true #　ポート待ち受けとかしてないとコンテナが終了してしまう対策。
    # command: python3 server.py
    volumes:
      - ./log:/log
    networks:
      - wantas-network

  scrape_client:
    build:
      context: ./scrape_client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: scrape_client_container
    tty: true
    # command: go run main.go
    volumes:
      - ./log:/log
    networks:
      - wantas-network

networks:
  wantas-network:
    external: true
