version: "3"
services:
  scrape_server:
    build:
      context: ./scrape_server
      dockerfile: Dockerfile
    container_name: scrape_server_container
    command: python3 server.py
    volumes:
      - ./log:/log
    networks:
      - test-network
    tty: true #　ポート待ち受けとかしてないとコンテナが終了してしまう対策。

  scrape_client:
    build:
      context: ./scrape_client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: scrape_client_container
    command: go run main.go
    tty: true
    volumes:
      - ./log:/log
    networks:
      - test-network

networks:
  test-network:
    external: true
